spring:
  application:
    name: notebook-llm
  docker:
    compose:
      enabled: false
  profiles:
    active: prod
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      chat:
        enabled: false
      embedding:
        enabled: false
    mistralai:
      chat:
        enabled: false
      embedding:
        api-key: ${MISTRALAI_API_KEY}
    ollama:
      base-url: http://${OLLAMA_BASE_URL}:11434
      chat:
        enabled: false
      embedding:
        enabled: false
    vectorstore:
      cassandra:
        initialize-schema: true
  jpa:
    open-in-view: false
  datasource:
    hikari:
      auto-commit: false
  servlet:
    multipart:
      max-file-size: 5MB
b2:
  application:
    key:
      value: ${B2_APPLICATION_KEY_VALUE}
      id: ${B2_APPLICATION_KEY_ID}
      name: ${B2_APPLICATION_KEY_NAME}
  bucket:
    id: ${B2_BUCKET_ID}